'use strict';

/**
 * HomeAwayService.js
 *
 * Says which side of a fixture is at home, so cards can put the visiting team
 * on the left and the title can read "Away @ Home".
 *
 * The providers don't carry this. Their team1/team2 is just the order the title
 * was written in, and 573 of 673 fixtures separate the sides with "vs", which
 * encodes nothing — the whole of soccer included. Inferring it from the
 * separator gets it wrong on real fixtures: the feed says "Florida A&M Rattlers
 * vs Miami Hurricanes" while ESPN has Miami at home.
 *
 * So this reads ESPN's scoreboards, which state homeAway per competitor, and
 * indexes them by team pair. A fixture ESPN doesn't list falls back to the
 * separator convention rather than blocking the card.
 *
 * The index is refreshed in the background and read synchronously: a catalog
 * build must never wait on ESPN, and a scoreboard that fails to load costs
 * orientation, never the catalog.
 */

const { request } = require('undici');

const HOST = 'https://site.web.api.espn.com/apis/site/v2/sports';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

const FETCH_TIMEOUT_MS = 6000;
// ESPN truncates at whatever `limit` says, but only up to a point: 400 returns
// exactly 400 for a busy soccer week, 1000 returns the real 897, and 2000
// returns 25 — the parameter stops being honoured and the response goes wrong.
const REQUEST_LIMIT = 1000;
const TTL_MS = 20 * 60 * 1000;         // scoreboards move slowly; fixtures don't swap venues
const COLD_WAIT_MS = 4000;             // most a first request will wait on a cold index
const STALE_SERVE_MS = 6 * 60 * 60 * 1000; // keep serving a stale index this long if ESPN is down

// Which ESPN scoreboards answer for a given addon category. Ordering is not
// significant — a fixture is looked up by team pair, so an event from the wrong
// board simply never matches.
const CATEGORY_BOARDS = {
  // Lite only enriches association football. This removes the NFL/CFL/AFL,
  // college, NBA/WNBA, MLB and NHL scoreboard polling workload.
  football: ['soccer/all']
};

const ALL_BOARDS = [...new Set(Object.values(CATEGORY_BOARDS).flat())];

// pair key -> the record of the event it names. One record is shared by every
// key that names the same event, which is most of them: a fixture whose two
// sides have six name variants each is thirty-six keys and one record.
let index = new Map();
let records = [];
let fetchedAt = 0;
let inFlight = null;
let lastStats = null;

// Kept between runs, so the first catalog request after a restart is not the
// one that waits on ESPN. Served stale and refreshed behind it, as always.
const INDEX_FILE = require('path').join(require('../config').DATA_DIR, 'homeaway.json');

// The version the file on disk is written under. A file an older build left
// behind holds a different shape entirely, and reading it as this one would
// hand every card a record with no kickoff and no networks. Refusing it costs
// one refresh, which the background loop was going to make anyway.
const FILE_VERSION = 2;

function restore() {
  try {
    const saved = JSON.parse(require('fs').readFileSync(INDEX_FILE, 'utf8'));
    if (!saved || saved.v !== FILE_VERSION) return;
    if (!Array.isArray(saved.events) || !Array.isArray(saved.keys)) return;
    if (!(Number(saved.fetchedAt) > 0)) return;
    if (Date.now() - Number(saved.fetchedAt) > STALE_SERVE_MS) return;
    const next = new Map();
    for (const [key, at] of saved.keys) {
      const rec = saved.events[at];
      if (rec) next.set(key, rec);
    }
    index = next;
    records = saved.events;
    fetchedAt = Math.min(Number(saved.fetchedAt), Date.now());
    lastStats = saved.stats || null;
  } catch (e) { /* first run, or unreadable */ }
}

function persist() {
  try {
    const fs = require('fs');
    fs.mkdirSync(require('path').dirname(INDEX_FILE), { recursive: true });
    // The records once, the keys as offsets into them. Writing a record out
    // under every key that names it is what made this file a megabyte, and the
    // sharing is the point of it: restoring must not clone it back apart.
    const at = new Map(records.map((rec, i) => [rec, i]));
    const keys = [];
    for (const [key, rec] of index) {
      const i = at.get(rec);
      if (i !== undefined) keys.push([key, i]);
    }
    const tmp = INDEX_FILE + '.tmp';
    fs.writeFileSync(tmp, JSON.stringify({ v: FILE_VERSION, fetchedAt, stats: lastStats, events: records, keys }));
    fs.renameSync(tmp, INDEX_FILE);
  } catch (e) { /* memory only, as before */ }
}

// Shared with TeamLogoService rather than copied: provider names and ESPN names
// only meet if both sides normalize identically, and two copies would drift.
const { normalize } = require('./TeamLogoService');

// league id (as ESPN event uids carry it) -> that league's crest. Generated by
// scripts/build-espn-teams.js from the same responses the team table comes
// from; ESPN keys league logos in a different id space than the uids do, so
// the pairing can only come from a response that states both.
let LEAGUE_LOGOS = {};
try {
  LEAGUE_LOGOS = require('./data/espn-leagues.json');
} catch {
  LEAGUE_LOGOS = {};      // absent table costs league crests, nothing else
}

function pairKey(a, b) {
  return a < b ? `${a}|${b}` : `${b}|${a}`;
}

/** UTC calendar day of an ISO timestamp, as YYYYMMDD. */
function dayOf(iso) {
  const t = Date.parse(iso);
  if (!Number.isFinite(t)) return '';
  const d = new Date(t);
  return `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, '0')}${String(d.getUTCDate()).padStart(2, '0')}`;
}

/**
 * A crest URL reduced to league + file, so ESPN's two spellings of the same
 * asset agree: the scoreboard serves .../teamlogos/nfl/500/scoreboard/lar.png
 * while the bundled table has .../teamlogos/nfl/500/lar.png. Both give nfl/lar.
 *
 * Matching on this rather than on names is what makes the alias problem go
 * away: the feed's "Los Angeles FC" and ESPN's "LAFC" never agree as strings,
 * but both resolve to the same crest.
 */
function logoKey(url) {
  if (!url || typeof url !== 'string') return '';
  const m = url.match(/\/teamlogos\/([^/]+)\/\d+(?:\/scoreboard)?\/([^/?#]+?)\.(?:png|svg|jpg)/i);
  return m ? `${m[1].toLowerCase()}/${m[2].toLowerCase()}` : '';
}

/**
 * Every name a team might be written under. The providers are not consistent
 * with ESPN — "Miami" for "Miami Hurricanes", "Bodø/Glimt" for "Bodo/Glimt" —
 * and indexing each variant against each of the opponent's costs a few hundred
 * keys per board while turning most near-misses into hits.
 */
function nameVariants(team) {
  if (!team) return [];
  const out = new Set();
  for (const field of [team.displayName, team.shortDisplayName, team.name, team.nickname, team.location, team.abbreviation]) {
    const n = normalize(field);
    if (n.length >= 2) out.add(n);
  }
  return [...out];
}

// The catalog lists fixtures up to ~10 weeks ahead, so orientation has to cover
// that whole horizon: a window of a few days left two thirds of soccer guessing.
const HORIZON_DAYS = 70;
const NEAR_DAYS = 9;         // as far out as a board is worth fetching a day at a time

// Boards a whole-month request does not answer for. soccer/all runs past the
// response cap inside a single month, and college football's month view is
// simply short: twenty-five games where the same month fetched a day at a time
// has sixty. Every other board was measured complete by the month — nfl, mlb
// and nhl each returned every event their per-day union held — so asking for
// their days as well would be sixty requests for nothing.
const PER_DAY_BOARDS = new Set(['soccer/all']);

function stampFor(now, offsetDays) {
  const d = new Date(now + offsetDays * 86400000);
  return `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, '0')}${String(d.getUTCDate()).padStart(2, '0')}`;
}

/**
 * The calendar months the horizon touches, as YYYYMM.
 *
 * Yesterday's month is in, not today's alone: on the first of a month a fixture
 * played last night is still on the catalog, and a board fetched only by month
 * would otherwise have no record of it.
 */
function monthsFor(now) {
  const first = new Date(now - 86400000);
  const last = new Date(now + HORIZON_DAYS * 86400000);
  const from = first.getUTCFullYear() * 12 + first.getUTCMonth();
  const to = last.getUTCFullYear() * 12 + last.getUTCMonth();
  const out = [];
  for (let n = from; n <= to; n++) out.push(`${Math.floor(n / 12)}${String((n % 12) + 1).padStart(2, '0')}`);
  return out;
}

/**
 * The requests a refresh makes.
 *
 * ESPN retired the `dates=A-B` range form and now answers 400 for it on every
 * board, so nothing here builds one. A single month covers a board's whole
 * horizon in three requests instead of five ranges, and the two boards a month
 * comes back short for are fetched a day at a time across the near window as
 * well — every event dropped from a response is a fixture that falls back to a
 * guess about which side is at home.
 */
function plan(now) {
  const jobs = [];
  const months = monthsFor(now);
  for (const board of ALL_BOARDS) {
    if (PER_DAY_BOARDS.has(board)) {
      for (let i = -1; i <= NEAR_DAYS; i++) jobs.push({ board, dates: stampFor(now, i) });
    }
    for (const dates of months) jobs.push({ board, dates });
  }
  return jobs;
}

/** Cap concurrent requests so a refresh doesn't open 60+ sockets at once. */
async function pool(items, limit, worker) {
  const out = [];
  let i = 0;
  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (i < items.length) {
      const idx = i++;
      out[idx] = await worker(items[idx]).then(
        v => ({ status: 'fulfilled', value: v }),
        e => ({ status: 'rejected', reason: e })
      );
    }
  });
  await Promise.all(runners);
  return out;
}

async function fetchBoard(board, dates) {
  const url = `${HOST}/${board}/scoreboard?dates=${dates}&limit=${REQUEST_LIMIT}`;
  const res = await request(url, {
    headers: { 'User-Agent': UA, Accept: 'application/json' },
    headersTimeout: FETCH_TIMEOUT_MS,
    bodyTimeout: FETCH_TIMEOUT_MS,
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS + 1000)
  });
  if (res.statusCode === 404) {
    // ESPN answers 404 for a board with no events on that date (an off-season
    // league). That is an empty day, not a failure.
    res.body.dump();
    return [];
  }
  if (res.statusCode !== 200) {
    res.body.dump();
    throw new Error(`${board}: HTTP ${res.statusCode}`);
  }
  const json = await res.body.json();
  // Single-league boards state their crest on the response; soccer/all carries
  // many competitions at once and states none, so those come from the event's
  // own league id instead.
  const league = (json?.leagues || [])[0];
  const boardLogo = league && (league.logos || []).map(l => l.href).find(Boolean);
  const events = Array.isArray(json?.events) ? json.events : [];
  if (boardLogo) for (const ev of events) if (ev && !ev.__boardLogo) ev.__boardLogo = boardLogo;
  return events;
}

/**
 * The television networks ESPN says will carry a fixture, at most three.
 *
 * Spelled exactly as ESPN spells them: "Prime Video", "FOX" and "SportsNet LA"
 * are what a viewer recognises, and normalising them would only produce a name
 * that is on nobody's remote. The two lists ESPN keeps overlap almost entirely,
 * which is why this is a de-duplication and not a concatenation.
 */
function networksOf(comp) {
  const out = [];
  const add = (name) => {
    const n = typeof name === 'string' ? name.trim() : '';
    if (!n || out.length >= 3 || out.includes(n)) return;
    out.push(n);
  };
  for (const b of comp?.broadcasts || []) for (const n of b?.names || []) add(n);
  for (const g of comp?.geoBroadcasts || []) add(g?.media?.shortName);
  return out;
}

function addEvent(map, list, event, board) {
  const comp = event?.competitions?.[0];
  const competitors = comp?.competitors;
  if (!Array.isArray(competitors) || competitors.length !== 2) return 0;

  const home = competitors.find(c => c.homeAway === 'home');
  const away = competitors.find(c => c.homeAway === 'away');
  if (!home || !away) return 0;

  // Neutral sites are NOT skipped. ESPN still designates a home side there and
  // names the event "A at B" accordingly — dropping them lost every such
  // fixture, including a regular-season NFL game ESPN flags neutralSite.
  // "@" in a listing means the designated visitor, not the deed to the stadium.

  // Board and day are part of every key, and both are load-bearing.
  //
  // Without the day, the two legs of a tie share one key and the first one
  // indexed decides both — so the return fixture is served the exact inverse of
  // its true orientation. Any home-and-home pair inside the horizon does this.
  //
  // Without the board, the same two universities meeting in another sport share
  // a key too: Tennessee host Vanderbilt at basketball, Vanderbilt host
  // Tennessee at baseball, and whichever is indexed first speaks for both.
  const day = dayOf(event.date);
  if (!day) return 0;
  const scope = `${board}:${day}`;

  // The competition this fixture belongs to, for the card's league crest.
  const uidLeague = /~l:([^~]+)/.exec(event.uid || '');
  const leagueLogo = (uidLeague && LEAGUE_LOGOS[uidLeague[1]]) || event.__boardLogo || null;
  let added = 0;

  const hLogo = logoKey(home.team && home.team.logo);
  const aLogo = logoKey(away.team && away.team.logo);
  const start = Date.parse(event.date);

  // Everything the responses already carried and were throwing away. A card
  // wants the kickoff ESPN has rather than the hour a provider typed, the
  // network the game is on, and whether it has started; all of it arrived with
  // the orientation and none of it cost a request.
  const rec = {
    // Whichever identity the crest key is compared against, so a crest lookup
    // can tell the sides apart. The name keys cannot use it — one event is
    // indexed under every variant of both names, and no single stored string
    // is the one a caller will arrive with — so they say it in the key instead.
    home: hLogo || normalize(home.team && home.team.displayName),
    league: leagueLogo,
    start: Number.isFinite(start) ? start : 0,
    status: typeof comp?.status?.type?.state === 'string' ? comp.status.type.state : '',
    net: networksOf(comp),
    venue: (comp?.venue?.fullName) || (event.venue && event.venue.fullName) || ''
  };

  // The crest pair is the strongest key of the two, since both sides of the
  // comparison come from the same ESPN asset namespace.
  if (hLogo && aLogo && hLogo !== aLogo) {
    const key = `L:${scope}:${pairKey(hLogo, aLogo)}`;
    if (!map.has(key)) { map.set(key, rec); added++; }
  }

  // Home side first in the key, away second. A sorted pair says which two teams
  // met and nothing about which of them was at home, and the record shared by
  // all of these keys cannot say it either — so the order the key hits in is
  // the answer, and a lookup tries both.
  const homeNames = nameVariants(home.team);
  const awayNames = nameVariants(away.team);
  for (const h of homeNames) {
    for (const a of awayNames) {
      if (h === a) continue;
      const key = `N:${scope}:${h}|${a}`;
      // Within one board on one day, a duplicate really is the same event.
      if (!map.has(key)) { map.set(key, rec); added++; }
    }
  }
  if (added) list.push(rec);
  return added;
}

async function rebuild() {
  const jobs = plan(Date.now());
  const results = await pool(jobs, 8, ({ board, dates }) => fetchBoard(board, dates));
  const next = new Map();
  const nextRecords = [];
  const stats = { requests: jobs.length, ok: 0, failed: [], events: 0, keys: 0, capped: [] };

  results.forEach((r, i) => {
    if (!r || r.status !== 'fulfilled') { stats.failed.push(`${jobs[i].board}@${jobs[i].dates}`); return; }
    stats.ok++;
    // A response exactly at the cap means ESPN truncated it and this window
    // needs splitting further. Recorded rather than guessed at.
    if (r.value.length >= REQUEST_LIMIT) stats.capped.push(`${jobs[i].board}@${jobs[i].dates}`);
    for (const ev of r.value) {
      stats.events++;
      stats.keys += addEvent(next, nextRecords, ev, jobs[i].board);
    }
  });

  // A board that stops answering costs every fixture on it its orientation and
  // its league crest, and nothing downstream complains: the catalog falls back
  // to the title's separator and the card still draws. That is how a live
  // instance sat at eleven answered requests out of eighty-four for weeks
  // without a line in the log, so a refresh that mostly fails now says so.
  if (stats.ok * 4 < stats.requests) {
    console.warn(`[HomeAway] only ${stats.ok} of ${stats.requests} scoreboard requests answered; orientation and league crests will be sparse`);
  }

  // Every request failing means ESPN or egress is down, not that fixtures lost
  // their venues — keep whatever the last good index was.
  if (!stats.ok && index.size) return lastStats;
  index = next;
  records = nextRecords;
  fetchedAt = Date.now();
  lastStats = stats;
  persist();
  return stats;
}

/**
 * Refresh if stale. Awaited by the catalog handler, but only ever blocks on a
 * cold start: once an index exists, a stale one is served while the refresh
 * runs behind it.
 */
async function ensureFresh() {
  const age = Date.now() - fetchedAt;
  if (index.size && age < TTL_MS) return;

  if (!inFlight) {
    inFlight = rebuild()
      .catch(() => null)
      .finally(() => { inFlight = null; });
  }
  if (!index.size) {
    // Cold, with nothing to serve: wait, but not indefinitely. A slow ESPN
    // costs this request its orientation, never its catalog. index.js primes
    // the index at boot so this path is rarely taken in practice.
    await Promise.race([inFlight, new Promise(r => setTimeout(r, COLD_WAIT_MS))]);
  }
}

/**
 * The event ESPN lists for this fixture, and whether the first side named is
 * the home one. Null when ESPN doesn't list it.
 *
 * Scoped to the boards that answer for this category and to the fixture's own
 * day (±1, since the provider's clock and ESPN's can straddle midnight). Both
 * are what keep a second meeting between the same two teams from inheriting the
 * first meeting's answer.
 *
 * Crest URLs are tried before names: the feed's team names and ESPN's rarely
 * agree letter-for-letter, but a resolved crest is the same asset on both
 * sides.
 */
function lookup(a, b, aLogo, bLogo, category, dateMs) {
  if (!a || !b || !index.size) return null;
  if (Date.now() - fetchedAt > STALE_SERVE_MS) return null;

  const t = Number(dateMs);
  // No date means no safe key: an undated fixture could be either leg of a tie,
  // and guessing between them is the failure this scoping exists to prevent.
  if (!Number.isFinite(t) || t <= 0) return null;

  // A category with no scoreboard has no evidence to offer, and searching every
  // board for it would only invite a cross-sport coincidence — a boxing card
  // matching two universities' names. Better to decline and let the caller fall
  // back to the title.
  const boards = CATEGORY_BOARDS[category];
  if (!boards) return null;
  const days = [0, -1, 1].map(off => {
    const d = new Date(t + off * 86400000);
    return `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, '0')}${String(d.getUTCDate()).padStart(2, '0')}`;
  });

  const la = logoKey(aLogo);
  const lb = logoKey(bLogo);
  const na = normalize(a);
  const nb = normalize(b);
  const logoPair = la && lb && la !== lb ? pairKey(la, lb) : null;
  const named = !!(na && nb && na !== nb);
  if (!logoPair && !named) return null;

  for (const board of boards) {
    for (const day of days) {
      const scope = `${board}:${day}`;
      if (logoPair) {
        const rec = index.get(`L:${scope}:${logoPair}`);
        if (rec && rec.home === la) return { rec, homeIsA: true };
        if (rec && rec.home === lb) return { rec, homeIsA: false };
      }
      if (named) {
        // The name keys are written home-first, so which order answers is which
        // side ESPN has at home.
        const asA = index.get(`N:${scope}:${na}|${nb}`);
        if (asA) return { rec: asA, homeIsA: true };
        const asB = index.get(`N:${scope}:${nb}|${na}`);
        if (asB) return { rec: asB, homeIsA: false };
      }
    }
  }
  return null;
}

/**
 * Orientation for a fixture, or null when ESPN doesn't list it.
 *
 * Returns { away, home } as the caller's own strings, not normalized ones.
 */
function orient(a, b, aLogo = null, bLogo = null, category = null, dateMs = null) {
  const hit = lookup(a, b, aLogo, bLogo, category, dateMs);
  if (!hit) return null;
  return hit.homeIsA
    ? { away: b, home: a, leagueLogo: hit.rec.league }
    : { away: a, home: b, leagueLogo: hit.rec.league };
}

/** What ESPN knows about a fixture beyond which side is at home. */
function details(a, b, aLogo = null, bLogo = null, category = null, dateMs = null) {
  const hit = lookup(a, b, aLogo, bLogo, category, dateMs);
  if (!hit) return null;
  const { start, status, net, venue, league } = hit.rec;
  // The networks are copied out, not handed over: one record answers for every
  // key that names the event, and a caller that sorted or trimmed the list in
  // place would be editing the index.
  return { start, status, net: Array.isArray(net) ? net.slice() : [], venue, leagueLogo: league };
}

/**
 * For tests: build the index from fixture events, as a refresh would. Reaching
 * ESPN is the one thing a test must not do, and everything below the request is
 * worth exercising for real.
 */
function seed(events, board) {
  const next = new Map();
  const list = [];
  for (const ev of events) addEvent(next, list, ev, board);
  index = next;
  records = list;
  fetchedAt = Date.now();
  return { keys: next.size, events: list.length };
}

function stats() {
  return { size: index.size, ageMs: fetchedAt ? Date.now() - fetchedAt : null, last: lastStats };
}

restore();

module.exports = {
  ensureFresh, orient, details, stats, normalize,
  _rebuild: rebuild, _plan: plan, _seed: seed, _restore: restore, _persist: persist
};
