'use strict';
const CACHE_TTL_MS=21600000,TIMEOUT_MS=3500,cache=new Map();
const num=v=>{if(v==null||v==='')return null;if(typeof v==='string'&&v.includes(':')){const p=v.split(':').map(Number);if(p.every(Number.isFinite))return p.reduce((a,x)=>a*60+x,0)}const n=Number(v);return Number.isFinite(n)?n:null};
const time=(r,s,m)=>{const x=num(r?.[s]);if(x!=null)return x;const y=num(r?.[m]);return y==null?null:y/1000};
function interval(type,row,provider){if(!row||typeof row!=='object')return null;const start=time(row,'start_sec','start_ms')??num(row.startTime)??num(row.start),end=time(row,'end_sec','end_ms')??num(row.endTime)??num(row.end);if(start==null||end==null||end<=start)return null;return{startTime:start,endTime:end,type:String(type||row.segment_type||row.segment||'intro').toLowerCase(),provider,action:String(row.action||'skip').toLowerCase(),confidence:Number.isFinite(Number(row.confidence))?Number(row.confidence):1,submissions:Number.isFinite(Number(row.submission_count??row.submissions))?Number(row.submission_count??row.submissions):null}}
function parseIntroDb(p){const out=[],add=(t,r)=>{const v=interval(t,r,'introdb');if(v)out.push(v)};if(Array.isArray(p?.segments))p.segments.forEach(r=>add(r.segment_type||r.segment||r.type,r));for(const t of ['intro','recap','outro']){const v=p?.[t];if(Array.isArray(v))v.forEach(r=>add(t,r));else if(v)add(t,v)}return out}
function merge(rows){const out=[];for(const r of rows.filter(Boolean).sort((a,b)=>a.startTime-b.startTime)){const p=out.find(x=>x.type===r.type&&x.action===r.action&&Math.abs(x.startTime-r.startTime)<=3&&Math.abs(x.endTime-r.endTime)<=3);if(!p){out.push({...r,evidence:[{provider:r.provider,confidence:r.confidence,submissions:r.submissions}]});continue}p.startTime=Math.min(p.startTime,r.startTime);p.endTime=Math.max(p.endTime,r.endTime);p.confidence=1-(1-p.confidence)*(1-r.confidence);p.evidence.push({provider:r.provider,confidence:r.confidence,submissions:r.submissions})}return out.slice(0,24)}
async function json(url,headers={}){const r=await fetch(url,{headers:{Accept:'application/json',...headers},redirect:'follow',signal:AbortSignal.timeout(TIMEOUT_MS)});if(!r.ok)return null;const t=await r.text();if(t.length>1048576)return null;try{return JSON.parse(t)}catch{return null}}
async function getSkipIntervals({imdbId,season,episode}){const imdb=String(imdbId||'').trim(),s=Number(season),e=Number(episode);if(!/^tt\d+$/.test(imdb)||!Number.isInteger(s)||!Number.isInteger(e))return[];const key=imdb+':'+s+':'+e,hit=cache.get(key);if(hit&&Date.now()-hit.at<CACHE_TTL_MS)return hit.rows;const base=String(process.env.INTRODB_API_URL||'https://api.introdb.app').replace(/\/$/,'');const headers={};if(process.env.INTRODB_API_KEY)headers['X-API-Key']=process.env.INTRODB_API_KEY;let rows=[];try{rows=parseIntroDb(await json(base+'/segments?imdb_id='+encodeURIComponent(imdb)+'&season='+s+'&episode='+e,headers))}catch{}rows=merge(rows);cache.set(key,{at:Date.now(),rows});return rows}
module.exports={getSkipIntervals,_parseIntroDb:parseIntroDb,_merge:merge};