'use strict';const assert=require('assert'),fs=require('fs'),path=require('path');const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');
assert(!html.includes('</script>\\\\n'),'literal escaped newlines must never leak into the HTML shell');
assert(html.includes('miniPlayerTitle')&&html.includes('miniPlayerTime')&&html.includes('miniPlayPause'),'mini player exposes metadata and transport');
assert(html.includes("classList.remove('player-open');document.body.classList.add('mini-player-active')"),'minimize restores browsing chrome');
assert(html.includes("body.mini-player-active>.mobile-bottom-nav"),'mobile dock remains interactive while minimized');
assert(html.includes("playerReturnToDetails&&currentDetailsMeta?'details':''"),'originating details view can be restored beneath mini player');
assert(html.includes("classList.remove('mini-player-active','details-open');document.body.classList.add('player-open')"),'expand returns to full player');
assert.equal((html.match(/timelineTrack\?\.addEventListener\('click'/g)||[]).length,0,'legacy duplicate timeline click seek removed');
assert(!html.includes("currentPlaybackSession = data.sessionId || null;\n        if(window.AIOTrickplay"),'trickplay must not race the primary stream startup');
assert(html.includes("progressVideo.addEventListener('playing'"),'trickplay waits for genuine playback');
assert(html.includes("setTimeout(()=>{if(generation===playbackGeneration&&session===currentPlaybackSession&&!progressVideo.paused)AIOTrickplay.start(session)},8000)"),'trickplay waits for stable playback before generation');
assert(html.includes("recoverPlayback(generation,'startup-timeout')"),'stalled Safari starts automatically escalate to compatibility');
assert(html.includes("#player-overlay.is-vod .player-timeline{display:block!important"),'inline mobile VOD exposes the scrubber');
assert(!html.includes('.player-timeline{display:none;}'),'mobile CSS cannot suppress the premium scrubber');
assert(html.includes("document.getElementById('playerStreamPicker').onclick=()=>openRawStreamPicker()"),'stream picker remains directly bound, independent of settings');
console.log('premium player UX contract passed');