'use strict';const assert=require('assert'),fs=require('fs'),path=require('path');const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');
const head=html.slice(0,html.indexOf('</head>'));assert(!/\\\\n/.test(head),'literal escaped newlines must never leak into the HTML shell');
assert(html.includes('miniPlayerTitle')&&html.includes('miniPlayerTime')&&html.includes('miniPlayPause'),'mini player exposes metadata and transport');
assert(html.includes("classList.remove('player-open');document.body.classList.add('mini-player-active')"),'minimize restores browsing chrome');
assert(html.includes("body.mini-player-active>.mobile-bottom-nav"),'mobile dock remains interactive while minimized');
assert(html.includes("playerReturnToDetails&&currentDetailsMeta?'details':''"),'originating details view can be restored beneath mini player');
assert(html.includes("classList.remove('mini-player-active','details-open');document.body.classList.add('player-open')"),'expand returns to full player');
assert.equal((html.match(/timelineTrack\?\.addEventListener\('click'/g)||[]).length,0,'legacy duplicate timeline click seek removed');
assert(!html.includes("recoverPlayback(generation,'startup-timeout')"),'healthy direct playback must never be escalated by a fixed startup timer');
assert(html.includes("video.addEventListener('error', failed, { once: true })"),'direct playback recovery is driven by an actual media error');
assert(html.includes("const appleCompatibility = isVod && isSafariBasedBrowser() && !standalonePwa && data.playback?.kind === 'direct'"),'browser Safari VOD uses compatibility on its first attempt while standalone PWA preserves direct playback');
assert(html.includes("compatibility:appleCompatibility"),'Safari compatibility is passed directly into initial playback');
assert(html.includes("const needsCompatibility = compatibility || (isVod && isSafariBasedBrowser() && !standalonePwa)"),'browser Safari prepares compatibility before attach while standalone PWA remains direct-play first');
assert(!html.includes("startup-timeout"),'Safari compatibility selection must not depend on a startup timer');
assert(html.includes("#player-overlay.is-vod .player-timeline{display:block!important"),'custom VOD scrubber is always exposed');
assert(!html.includes('AIOTrickplay'),'thumbnail trickplay is fully removed from the player');
assert(!html.includes('/trickplay-client.js'),'thumbnail trickplay client is not loaded');
assert(html.includes("viewport.className='continue-rail-viewport'"),'Continue and Upcoming use a dedicated horizontal scroll viewport');
assert(html.includes("rail.className='continue-rail-track'"),'Continue rail restores its dedicated track after generic card rendering');
assert(html.includes('grid-template-rows:repeat(2,max-content)!important'),'desktop Continue and Upcoming tracks use two stacked rows');
assert(html.includes('grid-template-rows:max-content!important'),'mobile Continue and Upcoming tracks use exactly one row');
assert(html.includes('touch-action:pan-x'),'mobile Continue rails explicitly accept horizontal touch gestures');
assert(!html.includes("host.className = 'grid continue-rows'"),'Continue page must not inherit the generic catalog grid layout');
assert(html.includes('@media(min-width:651px) and (hover:hover) and (pointer:fine)'),'desktop player has an explicit control layout');
assert(!html.includes('.player-timeline{display:none;}'),'mobile CSS cannot suppress the premium scrubber');
assert(html.includes("document.getElementById('playerStreamPicker').onclick=()=>openRawStreamPicker()"),'stream picker remains directly bound, independent of settings');

assert(html.includes("suppressSuggestionsUntilEdit=true"),'selecting a predictive title commits the search and suppresses reopening');
assert(html.includes("suggestionRequest++;searchInput.value=m.name||q"),'committed predictive search invalidates outstanding suggestion requests');
assert(html.includes("searchInput.blur();applySearch(searchInput.value)"),'predictive selection closes focus/dropdown before searching');
assert(html.includes("episodeWrap.className='episode-item'"),'episode actions use a valid sibling wrapper');
assert(html.includes("episodeWrap.appendChild(more)"),'episode action button is not nested inside the episode playback button');
assert(!html.includes("thumb.appendChild(more)"),'episode contextual action cannot be nested in the episode button');

assert(html.includes("#episodeStateMenu{z-index:260!important;pointer-events:auto!important}"),'episode state menu renders above the details surface');
assert(html.includes(".episode-item>.episode-more::after{content:'';position:absolute;inset:-9px"),'episode action has an enlarged touch hit target');
assert(html.includes("!event.target.closest?.('.episode-btn,.episode-more')"),'outside-click handling does not dismiss a menu from its own action trigger');
assert(html.includes("more.addEventListener('click', openEpisodeActions)"),'episode action has an explicit independent click handler');
assert(html.includes("const availableNow=next.available!==false"),'next episode preparation distinguishes unavailable/future episodes');
assert(html.includes("currentNextEpisode.availableNow===false"),'auto-next countdown cannot start for an unavailable episode');
assert(html.includes("if(next&&next.availableNow===false)"),'ended playback has a caught-up path');
assert(html.includes("fetch('/api/v1/progress',{cache:'no-store'})"),'caught-up transition refreshes authoritative progress before Upcoming resolution');
assert(html.includes("await closePlayer(true);"),'caught-up playback exits the player after persisting state');
assert(html.includes("typeof video.webkitSetPresentationMode==='function'"),'PiP supports the WebKit presentation mode used on iPhone');
assert(html.includes("video.webkitPresentationMode==='picture-in-picture'"),'iPhone PiP control can toggle the active WebKit PiP session');
assert(html.includes("#player-overlay.is-vod #playerPip,#player-overlay.is-vod #playerFullscreen{display:inline-flex!important"),'mobile VOD exposes PiP beside the custom transport controls');
assert(html.includes('function armResumePosition(video,generation)'), 'resume position is retained until the media timeline becomes seekable');
assert(html.includes("video.addEventListener('progress',tryResume)"), 'compatibility HLS retries resume as segments establish seekable ranges');
assert(html.includes("video.addEventListener('canplay',tryResume)"), 'resume is retried when Safari can actually seek the compatibility stream');
assert(html.includes('applyResumePosition(video);\n          started = true;'), 'HLS manifest readiness attempts the saved resume before playback starts');
assert(!html.includes('resumeSeconds >= video.duration * 0.90'), 'playback resume is not suppressed by Continue-Watching completion thresholds');
assert(!html.includes("#player-overlay.is-vod #playerMinimize,\n    #player-overlay.is-vod #playerPip,\n    #player-overlay.is-vod #playerStreamPicker"),'unified VOD chrome must not globally hide PiP');
assert(html.includes("display:inline-flex!important;visibility:visible!important;opacity:1!important;"),'final mobile PiP rule explicitly defeats legacy visibility rules');
assert(html.includes("#player-overlay.is-vod:not(.mini) #playerPip"),'mobile PiP has an independent player anchor');
assert(html.includes("right:max(18px,env(safe-area-inset-right,0px))!important"),'PiP is docked to the lower-right safe area');
assert(html.includes("html.aioplay-standalone #player-overlay.is-vod:not(.mini) #playerPip"),'installed PWA explicitly exposes the PiP control');
assert(html.includes("video.webkitSupportsPresentationMode('picture-in-picture')"),'installed iOS PWA checks the WebKit PiP capability directly');
assert(html.includes("if(supportsWebkitPip())"),'Apple PiP prefers the WebKit presentation path before the standards API');
console.log('premium player UX contract passed');