'use strict';const assert=require('assert'),fs=require('fs'),path=require('path');const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');
const head=html.slice(0,html.indexOf('</head>'));assert(!/\\\\n/.test(head),'literal escaped newlines must never leak into the HTML shell');
assert(html.includes('miniPlayerTitle')&&html.includes('miniPlayerTime')&&html.includes('miniPlayPause'),'mini player exposes metadata and transport');
assert(html.includes("classList.remove('player-open');document.body.classList.add('mini-player-active')"),'minimize restores browsing chrome');
assert(html.includes("body.mini-player-active>.mobile-bottom-nav"),'mobile dock remains interactive while minimized');
assert(html.includes("playerReturnToDetails&&currentDetailsMeta?'details':''"),'originating details view can be restored beneath mini player');
assert(html.includes("classList.remove('mini-player-active','details-open');document.body.classList.add('player-open')"),'expand returns to full player');
assert.equal((html.match(/timelineTrack\?\.addEventListener\('click'/g)||[]).length,0,'legacy duplicate timeline click seek removed');
assert(!html.includes("recoverPlayback(generation,'startup-timeout')"),'healthy direct playback must never be escalated by a fixed startup timer');
assert(html.includes("video.addEventListener('error', failed, { once: true })"),'direct playback recovery is driven by an actual media error');
assert(html.includes("#player-overlay.is-vod .player-timeline{display:block!important"),'custom VOD scrubber is always exposed');
assert(!html.includes('AIOTrickplay'),'thumbnail trickplay is fully removed from the player');
assert(!html.includes('/trickplay-client.js'),'thumbnail trickplay client is not loaded');
assert(html.includes('grid-template-rows:repeat(2,auto)!important'),'desktop Continue and Upcoming rails use two stacked rows');
assert(html.includes('grid-template-rows:1fr!important'),'mobile Continue and Upcoming rails use one row');
assert(html.includes('@media(min-width:651px) and (hover:hover) and (pointer:fine)'),'desktop player has an explicit control layout');
assert(!html.includes('.player-timeline{display:none;}'),'mobile CSS cannot suppress the premium scrubber');
assert(html.includes("document.getElementById('playerStreamPicker').onclick=()=>openRawStreamPicker()"),'stream picker remains directly bound, independent of settings');
console.log('premium player UX contract passed');