'use strict';const assert=require('assert'),fs=require('fs'),path=require('path');
const remote=fs.readFileSync(path.join(__dirname,'../public/remote-playback.js'),'utf8');
const html=fs.readFileSync(path.join(__dirname,'../public/index.html'),'utf8');
const server=fs.readFileSync(path.join(__dirname,'../src/index.js'),'utf8');
assert(remote.includes('DEFAULT_MEDIA_RECEIVER_APP_ID'),'Cast uses the Google Default Media Receiver');
assert(remote.includes('ORIGIN_SCOPED'),'Cast auto-join is scoped to the AIOPlay origin');
assert(remote.includes('requestSession'),'remote layer supports explicit receiver selection');
assert(remote.includes('RemotePlayerController'),'remote layer tracks receiver state');
assert(remote.includes('webkitShowPlaybackTargetPicker'),'remote layer supports native Safari AirPlay selection');
assert(remote.includes('webkitplaybacktargetavailabilitychanged'),'AirPlay availability is tracked');
assert(remote.includes('webkitcurrentplaybacktargetiswirelesschanged'),'AirPlay connection state is tracked');
assert(remote.includes('PLAYER_STATE_CHANGED'),'Cast completion state is tracked');
assert(html.includes('id="playerCast"'),'player exposes Cast control');
assert(html.includes('id="playerAirPlay"'),'player exposes AirPlay control');
assert(html.includes('x-webkit-airplay="allow"'),'player explicitly permits Safari video AirPlay');
assert(html.includes('function setAirPlayAlternative'),'player can expose a receiver-fetchable AirPlay alternative');
assert(html.includes("source.type = 'application/vnd.apple.mpegurl'"),'AirPlay alternative is advertised as HLS');
assert(html.includes('setAirPlayAlternative(video, playbackUrl)'),'hls.js playback retains the prepared HLS URL for AirPlay');
assert(html.includes("fetch('/api/v1/playback/'+encodeURIComponent(currentPlaybackSession)+'/remote'"),'Cast requests a receiver-safe playback URL');
assert(html.includes("document.getElementById('video')?.pause()"),'local playback pauses only after remote load succeeds');
assert(html.includes('playerPosition(video)-10'),'back 10 uses the active remote/local timeline');
assert(html.includes('playerPosition(video)+10'),'forward 10 uses the active remote/local timeline');
assert(html.includes('togglePlayerPlayback(video)'),'play/pause follows active remote playback');
assert(html.includes("video.dispatchEvent(new Event('ended'))"),'remote completion feeds the normal episode-completion path');
assert(server.includes("app.post('/api/v1/playback/:sessionId/remote'"),'server exposes playback-scoped remote URL issuing');
assert(server.includes("externalPlayback.issue(target,{leaseId:lease.id})"),'remote URL stays bound to the active playback lease');
assert(!remote.includes('/apple-hls'),'remote playback does not alter Safari compatibility playback');
console.log('remote playback and AirPlay contract passed');